#ifndef ANTESTL_BACKEND_EXCEPTIONS_HPP
#define ANTESTL_BACKEND_EXCEPTIONS_HPP

#define GOT_ERROR_FROM_OPC      0xE0
#define NO_DATA_FROM_DEVICE     0xE1
#define GOT_ERROR_FROM_WRITE    0xE2
#define GOT_ERROR_FROM_DEVICE   0xE3

#define NO_CONNECTION           0xEF

#define FREQ_OUT_OF_BOUND       0xF1

#endif //ANTESTL_BACKEND_EXCEPTIONS_HPP
