#ifndef ANTESTL_BACKEND_TEST_JSON_REQUESTS_HPP
#define ANTESTL_BACKEND_TEST_JSON_REQUESTS_HPP

#include <string>

std::string connection_task = "{\n"
                              "\t\"task\": {\n"
                              "\t\t\"type\": \"connect\",\n"
                              "\t\t\"args\": {\n"
                              "\t\t\t\"m9807a\": \"TCPIP0::LINK-PC::inst0::INSTR\"\n"
                              "\t\t}\n"
                              "\t}}";

std::string connection_task_2 = "{\n"
                                "\t\"task\": {\n"
                                "\t\t\"type\": \"connect\",\n"
                                "\t\t\"args\": {\n"
                                "\t\t\t\"m9807a\": \"TCPIP0::LINK-PC::inst0::INSTR\",\n"
                                "\t\t\t\"ext_gen\": \"TCPIP0::localhost::5026::SOCKET\",\n"
                                "\t\t\t\"rbd_2\": \"TCPIP0::localhost::5001::SOCKET;TCPIP0::localhost::5002::SOCKET\"\n"
                                "\t\t}\n"
                                "\t}}";

std::string configure_task = "{\n"
                             "\t\"task\": {\n"
                             "\t\t\"type\": \"configure\",\n"
                             "\t\t\"args\": {\n"
                             "\t\t\t\"meas_type\": 1,\n"
                             "\t\t\t\"rbw\": 1e3,\n"
                             "\t\t\t\"source_port\": 1,\n"
                             "\t\t\t\"external\": false\n"
                             "\t\t}\n"
                             "\t}\n"
                             "}";

std::string set_power_task = "{\n"
                             "\t\"task\": {\n"
                             "\t\t\"type\": \"set_power\",\n"
                             "\t\t\"args\": {\n"
                             "\t\t\t\"value\": -13.2\n"
                             "\t\t}\n"
                             "\t}\n"
                             "}";

std::string set_freq_task = "{\n"
                            "\t\"task\": {\n"
                            "\t\t\"type\": \"set_freq\",\n"
                            "\t\t\"args\": {\n"
                            "\t\t\t\"value\": 3.7e9\n"
                            "\t\t}\n"
                            "\t}\n"
                            "}";

std::string set_freq_range_task = "{\n"
                                  "\t\"task\": {\n"
                                  "\t\t\"type\": \"set_freq_range\",\n"
                                  "\t\t\"args\": {\n"
                                  "\t\t\t\"start\": 2e9,\n"
                                  "\t\t\t\"stop\": 5.8e9,\n"
                                  "\t\t\t\"points\": 201\n"
                                  "\t\t}\n"
                                  "\t}\n"
                                  "}";

std::string change_path_task = "{\n"
                               "\t\"task\": {\n"
                               "\t\t\"type\": \"change_path\",\n"
                               "\t\t\"args\": {\n"
                               "\t\t\t\"switch_1\": 1,\n"
                               "\t\t\t\"switch_2\": 5,\n"
                               "\t\t\t\"switch_3\": 2,\n"
                               "\t\t\t\"switch_4\": 4\n"
                               "\t\t}\n"
                               "\t}\n"
                               "}";

std::string get_data_task = "{\n"
                            "\t\"task\": {\n"
                            "\t\t\"type\": \"get_data\",\n"
                            "\t\t\"args\": {\n"
                            "\t\t\t\"ports\": [2, 3, 4, 5, 6, 7, 8]\n"
                            "\t\t}\n"
                            "\t}\n"
                            "}";

std::string task_list_test = "{"
                             "\"task_list\": [\n"
                             "\t\t{\n"
                             "\t\t\"type\": \"connect\",\n"
                             "\t\t\"args\": {\n"
                             "\t\t\t\"m9807a\": \"TCPIP0::LINK-PC::inst0::INSTR\"\n"
                             "\t\t\t}\n"
                             "\t\t},\n"
                             "\t\t{\n"
                             "\t\t\t\"type\": \"configure\",\n"
                             "\t\t\t\"args\": {\n"
                             "\t\t\t\t\"meas_type\": 0,\n"
                             "\t\t\t\t\"rbw\": 1000,\n"
                             "\t\t\t\t\"source_port\": 1,\n"
                             "\t\t\t\t\"external\": false\n"
                             "\t\t\t}\n"
                             "\t\t},\n"
                             "\t\t{\n"
                             "\t\t\t\"type\": \"set_power\",\n"
                             "\t\t\t\"args\": {\n"
                             "\t\t\t\t\"value\": -20\n"
                             "\t\t\t}\n"
                             "\t\t},\n"
                             "\t\t{\n"
                             "\t\t\t\"type\": \"set_freq_range\",\n"
                             "\t\t\t\"args\": {\n"
                             "\t\t\t\t\"start\": 1000000000,\n"
                             "\t\t\t\t\"stop\": 9000000000,\n"
                             "\t\t\t\t\"points\": 11\n"
                             "\t\t\t},\n"
                             "\t\t\t\"nested\": 1\n"
                             "\t\t},\n"
                             "\t\t{\n"
                             "\t\t\t\"type\": \"get_data\",\n"
                             "\t\t\t\"args\": {\n"
                             "\t\t\t\t\"ports\": [2, 5, 4]\n"
                             "\t\t\t},\n"
                             "\t\t\t\"nested\": 0\n"
                             "\t\t}\n"
                             "\t]}";

std::string task_list_test_2 = "{"
                               "\"task_list\": [\n"
                               "\t\t{\n"
                               "\t\t\"type\": \"connect\",\n"
                               "\t\t\"args\": {\n"
                               "\t\t\t\"m9807a\": \"TCPIP0::LINK-PC::inst0::INSTR\"\n"
                               "\t\t\t},\n"
                               "\t\t\"nested\": 0\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"configure\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"meas_type\": 0,\n"
                               "\t\t\t\t\"rbw\": 1000,\n"
                               "\t\t\t\t\"source_port\": 1,\n"
                               "\t\t\t\t\"external\": false\n"
                               "\t\t\t},\n"
                               "\t\t\"nested\": 1\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"set_power\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"value\": -20\n"
                               "\t\t\t}\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"set_freq_range\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"start\": 1000000000,\n"
                               "\t\t\t\t\"stop\": 9000000000,\n"
                               "\t\t\t\t\"points\": 11\n"
                               "\t\t\t},\n"
                               "\t\t\t\"nested\": 1\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"get_data\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"ports\": [2, 5, 4]\n"
                               "\t\t\t},\n"
                               "\t\t\t\"nested\": 0\n"
                               "\t\t}\n"
                               "\t]}";

std::string task_list_test_3 = "{\"task_list\": [\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"connect\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"m9807a\": \"TCPIP0::LINK-PC::inst0::INSTR\",\n"
                               "\t\t\t\t\"demo_rbd\": \"addr1;addr2;addr3\"\n"
                               "\t\t\t\t}\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"configure\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"meas_type\": 0,\n"
                               "\t\t\t\t\"rbw\": 1000,\n"
                               "\t\t\t\t\"source_port\": 1,\n"
                               "\t\t\t\t\"external\": false\n"
                               "\t\t\t}\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"set_power\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"value\": -20\n"
                               "\t\t\t}\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"set_freq_range\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"start\": 1000000000,\n"
                               "\t\t\t\t\"stop\": 9000000000,\n"
                               "\t\t\t\t\"points\": 11\n"
                               "\t\t\t},\n"
                               "\t\t\t\"nested\": 1\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"set_angle_range\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"start\": -30,\n"
                               "\t\t\t\t\"stop\": 30,\n"
                               "\t\t\t\t\"points\": 11,\n"
                               "\t\t\t\t\"axis\": 0\n"
                               "\t\t\t},\n"
                               "\t\t\t\"nested\": 2\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"set_angle_range\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"start\": -20,\n"
                               "\t\t\t\t\"stop\": 20,\n"
                               "\t\t\t\t\"points\": 11,\n"
                               "\t\t\t\t\"axis\": 1\n"
                               "\t\t\t},\n"
                               "\t\t\t\"nested\": 3\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"set_angle_range\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"start\": -10,\n"
                               "\t\t\t\t\"stop\": 10,\n"
                               "\t\t\t\t\"points\": 11,\n"
                               "\t\t\t\t\"axis\": 2\n"
                               "\t\t\t},\n"
                               "\t\t\t\"nested\": 4\n"
                               "\t\t},\n"
                               "\t\t{\n"
                               "\t\t\t\"type\": \"get_data\",\n"
                               "\t\t\t\"args\": {\n"
                               "\t\t\t\t\"ports\": [2, 5, 4]\n"
                               "\t\t\t},\n"
                               "\t\t\t\"nested\": 0\n"
                               "\t\t}\n"
                               "\t]}";

std::string task_list_test_4 = "{\n"
                               "\t\"task_list\": [\n"
                               "\t{\n"
                               "\t\t\"type\": \"connect\",\n"
                               "\t\t\"args\": \n"
                               "\t\t{\n"
                               "\t\t\t\"m9807a\": \"TCPIP0::LINK-PC::inst0::INSTR\",\n"
                               "\t\t\t\"demo_rbd\": \"addr1\"\n"
                               "\t\t}\n"
                               "\t},\n"
                               "\t{\n"
                               "\t\t\"type\": \"configure\",\n"
                               "\t\t\"args\": \n"
                               "\t\t{\n"
                               "\t\t\t\"meas_type\": 0,\n"
                               "\t\t\t\"rbw\": 1000,\n"
                               "\t\t\t\"source_port\": 1,\n"
                               "\t\t\t\"external\": false\n"
                               "\t\t}\n"
                               "\t},\n"
                               "\t{\n"
                               "\t\t\"type\": \"set_power\",\n"
                               "\t\t\"args\": \n"
                               "\t\t{\n"
                               "\t\t\t\"value\": -20\n"
                               "\t\t}\n"
                               "    },\n"
                               "\t{\n"
                               "\t\t\"type\": \"set_freq_range\",\n"
                               "\t\t\"args\": \n"
                               "\t\t{\n"
                               "\t\t\t\"start\": 1000000000,\n"
                               "\t\t\t\"stop\": 9000000000,\n"
                               "\t\t\t\"points\": 11\n"
                               "\t\t},\n"
                               "\t\t\"nested\": 1\n"
                               "\t},\n"
                               "\t{\n"
                               "\t\t\"type\": \"set_angle_range\",\n"
                               "\t\t\"args\": \n"
                               "\t\t{\n"
                               "\t\t\t\"start\": -30,\n"
                               "\t\t\t\"stop\": 30,\n"
                               "\t\t\t\"points\": 11,\n"
                               "\t\t\t\"axis\": 0\n"
                               "\t\t},\n"
                               "\t\t\"nested\": 2\n"
                               "\t},\n"
                               "\t{\n"
                               "\t\t\"type\": \"get_data\",\n"
                               "\t\t\"args\": \n"
                               "\t\t{\n"
                               "\t\t\t\"ports\": [2, 5, 4]\n"
                               "\t\t},\n"
                               "\t\t\"nested\": 0\n"
                               "    }]\n"
                               "}";

#endif //ANTESTL_BACKEND_TEST_JSON_REQUESTS_HPP
